linters:
  disable-all: true
  enable:
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - unused
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  # - containedctx
  - contextcheck
  - copyloopvar
  - decorder
  - dogsled
  # - dupl
  - dupword
  - durationcheck
  # - errchkjson
  - errname
  # - errorlint
  - fatcontext
  - forbidigo
  # - forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  # - gochecknoinits
  - gochecksumtype
  # - gocognit
  - goconst
  - gocritic
  - gocyclo
  # - godot
  # - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  # - gosec
  - gosmopolitan
  - grouper
  - iface
  - importas
  # - inamedparam
  - interfacebloat
  # - intrange
  - loggercheck
  # - maintidx
  - makezero
  - mirror
  - misspell
  - musttag
  - nakedret
  - nilerr
  - nlreturn
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - stylecheck
  - tagalign
  - tenv
  - testableexamples
  - thelper
  - tparallel
  - unconvert
  - unparam
  - usestdlibvars
  - wastedassign
  - whitespace
  - zerologlint

linters-settings:
  gofmt:
    simplify: false
  goconst:
    ignore-tests: true
  gocyclo:
    min-complexity: 32
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to mention the specific linter being suppressed
  # goheader:
  #   template-path: '.github/.golangci.goheader.template'
  #   values:
  #     regexp:
  #       copyright-year: 20[2-9]\d

issues:
  max-issues-per-linter: 0
  max-same-issues: 0