// Code generated by "stringer -type=Event"; DO NOT EDIT.

package informationaltype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChangeSummary-1]
	_ = x[DetectionsSummary-4]
	_ = x[FlowsSummary-3]
	_ = x[None-0]
	_ = x[PullSummary-2]
}

const _Event_name = "NoneChangeSummaryPullSummaryFlowsSummaryDetectionsSummary"

var _Event_index = [...]uint8{0, 4, 17, 28, 40, 57}

func (i Event) String() string {
	if i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
