// Package informationaltype provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package informationaltype

// Defines values for Event.
const (
	ChangeSummary     Event = 1
	DetectionsSummary Event = 4
	FlowsSummary      Event = 3
	None              Event = 0
	PullSummary       Event = 2
)

// Event defines model for Event.
type Event uint64
