// Package informationaltype provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package informationaltype

// Defines values for Event.
const (
	ChangeSummary     Event = 1
	DetectionsSummary Event = 4
	FlowsSummary      Event = 3
	None              Event = 0
	PullSummary       Event = 2
	Summary           Event = 5
)

// Event defines model for Event.
type Event uint64
