// Package verdictcode provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20230513000919-14548c7e7bbe DO NOT EDIT.
package verdictcode

// Defines values for Code.
const (
	DDN01  Code = 1001
	FNI001 Code = 1
	FNI002 Code = 2
	FNI003 Code = 3
	MDN01  Code = 1021
	MDN02  Code = 1022
	MDN03  Code = 1023
	MDN04  Code = 1024
	TSN01  Code = 1011
	UNK    Code = 0
)

// Code defines model for Code.
type Code uint64
