// Package verdictcode provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.5-0.20230818123536-bd9ff2a1313d DO NOT EDIT.
package verdictcode

// Defines values for Code.
const (
	DDN01  Code = 1001
	FNI001 Code = 1
	FNI002 Code = 2
	FNI003 Code = 3
	FNI004 Code = 4
	FNI005 Code = 5
	FNI006 Code = 6
	FNI007 Code = 7
	FNI008 Code = 8
	MDN01  Code = 1021
	MDN02  Code = 1022
	MDN03  Code = 1023
	MDN04  Code = 1024
	MDN05  Code = 1025
	MDN06  Code = 1026
	MDN07  Code = 1027
	MDN08  Code = 1028
	STN001 Code = 1101
	STN002 Code = 1102
	STN003 Code = 1103
	STN004 Code = 1104
	STN005 Code = 1105
	STN006 Code = 1106
	STN007 Code = 1107
	STN008 Code = 1108
	STN009 Code = 1109
	TSN01  Code = 1011
	UNK    Code = 0
)

// Code defines model for Code.
type Code uint64
