// Code generated by "stringer -type=Code"; DO NOT EDIT.

package verdictcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNK-0]
	_ = x[FNI001-1]
	_ = x[FNI002-2]
	_ = x[FNI003-3]
	_ = x[DDN01-1001]
}

const (
	_Code_name_0 = "UNKFNI001FNI002FNI003"
	_Code_name_1 = "DDN01"
)

var (
	_Code_index_0 = [...]uint8{0, 3, 9, 15, 21}
)

func (i Code) String() string {
	switch {
	case i <= 3:
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case i == 1001:
		return _Code_name_1
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
