// Package lockfile provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package lockfile

// Defines values for Lockfile.
const (
	None            Lockfile = ""
	PackageLockJSON Lockfile = "package-lock.json"
	PoetryLock      Lockfile = "poetry.lock"
)

// Lockfile defines model for Lockfile.
type Lockfile string
