// Package lockfile provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package lockfile

// Defines values for Lockfile.
const (
	None            Lockfile = ""
	PackageLockJSON Lockfile = "package-lock.json"
	PoetryLock      Lockfile = "poetry.lock"
)

// Lockfile defines model for Lockfile.
type Lockfile string
