// Package severity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.5-0.20230818123536-bd9ff2a1313d DO NOT EDIT.
package severity

// Defines values for Severity.
const (
	High   Severity = "high"
	Low    Severity = "low"
	Medium Severity = "medium"
)

// Severity defines model for Severity.
type Severity string
