// Package severity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20230513000919-14548c7e7bbe DO NOT EDIT.
package severity

// Defines values for Severity.
const (
	High   Severity = "high"
	Low    Severity = "low"
	Medium Severity = "medium"
)

// Severity defines model for Severity.
type Severity string
