// Package ecosystem provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.5-0.20230818123536-bd9ff2a1313d DO NOT EDIT.
package ecosystem

// Defines values for Ecosystem.
const (
	None Ecosystem = 0
	Npm  Ecosystem = 1
	Pypi Ecosystem = 2
)

// Ecosystem defines model for Ecosystem.
type Ecosystem uint64
