// Package ecosystem provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.1-0.20230608084521-ad62d73d8d22 DO NOT EDIT.
package ecosystem

// Defines values for Ecosystem.
const (
	None Ecosystem = 0
	Npm  Ecosystem = 1
	Pypi Ecosystem = 2
)

// Ecosystem defines model for Ecosystem.
type Ecosystem uint64
