// Package ecosystem provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package ecosystem

// Defines values for Ecosystem.
const (
	None Ecosystem = 0
	Npm  Ecosystem = 1
	Pypi Ecosystem = 2
)

// Ecosystem defines model for Ecosystem.
type Ecosystem uint64
