openapi: "3.1"
info:
  version: 1.0.0
  title: Manifest Model
  termsOfService: http://swagger.io/terms/
  contact:
    name: The Engineering Team
    email: engineering@garnet.ai
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /temp-severity:
    post:
      operationId: temp-manifest
      description: This is just to let openapi-codegen generate the Manifest model.
      responses:
        default:
          description: The Manifest model.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Manifest'
components:
  schemas:
    Manifest:
      type: string
      enum:
        - ""
        - "package.json"
      x-enum-varnames:
        - None
        - PackageJSON