// Package manifest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package manifest

// Defines values for Manifest.
const (
	None        Manifest = ""
	PackageJSON Manifest = "package.json"
)

// Manifest defines model for Manifest.
type Manifest string
