name: linting

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["main"]
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["main"]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21' ]
    steps:
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Verify the dependencies
        run: |
          go mod verify
          go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.57.1
          args: --timeout 20m0s --verbose --out-${IGNORE_FUTURE_WARNINGS}format tab

