name: linting

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["main"]
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["main"]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20' ]
    steps:
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Verify the dependencies
        run: |
          go mod verify
          go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 15m0s --verbose --out-${IGNORE_FUTURE_WARNINGS}format tab

