openapi: "3.0.3"
info:
  version: 1.0.0
  title: npm API
  description: This API interfaces clients with our database of verdicts.
  termsOfService: http://swagger.io/terms/
  contact:
    name: The Engineering Team
    email: engineering@garnet.ai
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /temp-problem:
    post:
      operationId: temp-problem
      description: This is just to let openapi-codegen generate the Problem model.
      responses:
        default:
          description: The Problem model.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /temp-verdict:
    post:
      operationId: temp-verdict
      description: This is just to let openapi-codegen generate the Verdict model.
      responses:
        default:
          description: The Verdict model.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Verdict'
components:
  schemas:
    Verdict:
      type: object
      required:
        - message
        - severity
        - metadata
      properties:
        message:
          type: string
          x-oapi-codegen-extra-tags:
            validate: mandatory
            human: the verdict message
        severity:
          type: string
          enum:
            - "low"
            - "medium"
            - "high"
          x-oapi-codegen-extra-tags:
            validate: mandatory,severity
            human: the verdict severity
        metadata:
          type: object
      example:
        message: "npm install spawned a process"
        severity: "medium"
        metadata:
          commandline: "sh -c node-gyp-build"
          executable_path: "/bin/sh"
          file_descriptor: ""
          npm_package_name: "utf-8-validate"
          npm_package_version: "5.0.10"
          parent_name: "node"
          server_ip: ""
          server_port: 0
    Problem:
      type: object
      required:
        - type
        - title
        - detail
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
      example:
        type: "Package not analysed yet"
        title: "Package not analysed yet"
        detail: "https:/docs.listen.dev/lstn-api/troubleshooting/not-found"