openapi: "3.0.3"
info:
  version: 1.0.0
  title: npm API
  description: This API interfaces clients with our database of verdicts.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Francesco Di Donato
    email: francesco@garnet.ai
    url: https://listen.dev
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://127.0.0.1:3000
    description: The locally running server (port may change, see .env)
  - url: https://npm-staging.listen.dev
    description: The staging server
paths:
  /api/analysis:
    post:
      operationId: analysis
      description: This API receives a base64 encoded package-lock.json file and returns verdicts for each dependency listed in it.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Verdict'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    NameVersionShasum:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: name of the package
        version:
          type: string
          description: version of the package
        shasum:
          type: string
          description: shasum of the package
      example:
        name: "@vue/devtools"
        version: "6.5.0"
        shasum: "32b09b0e3ca7b757802f9a0b9ded8c2035ce7874"

    Verdict:
      type: object
      required:
        - message
        - priority
        - metadata
      properties:
        message:
          type: string
        priority:
          type: string
          enum:
            - "low"
            - "medium"
            - "high"
        metadata:
          type: object
      example:
        message: "npm install spawned a process"
        priority: "medium"
        metadata:
          commandline: "sh -c node-gyp-build"
          executable_path: "/bin/sh"
          file_descriptor: ""
          npm_package_name: "utf-8-validate"
          npm_package_version: "5.0.10"
          parent_name: "node"
          server_ip: ""
          server_port: 0
    
    Problem:
      type: object
      required:
        - type
        - title
        - detail
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
      example:
        type: "Package not analysed yet"
        title: "Package not analysed yet"
        detail: "https:/docs.listen.dev/lstn-api/troubleshooting/not-found"