// Package category provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package category

// Defines values for Category.
const (
	AdjacentNetwork Category = "adjacent network"
	Cis             Category = "cis"
	Container       Category = "container"
	Cve             Category = "cve"
	Filesystem      Category = "filesystem"
	Local           Category = "local"
	Network         Category = "network"
	Physical        Category = "physical"
	Process         Category = "process"
	Users           Category = "users"
)

// Category defines model for Category.
type Category string
