openapi: "3.0.3"
info:
  version: 1.0.0
  title: Category Model
  termsOfService: http://swagger.io/terms/
  contact:
    name: The Engineering Team
    email: engineering@garnet.ai
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /temp-category:
    post:
      operationId: temp-category
      description: This is just to let openapi-codegen generate the Category model.
      responses:
        default:
          description: The Category model.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
components:
  schemas:
    Category:
      type: string
      enum:
        - "filesystem"
        - "process"
        - "network"
        - "users"
        - "container"
        - "cis"
        - "cve"
        - "adjacent network"
        - "local"
        - "physical"